<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EmployeeSeeder extends Seeder
{
    public function run(): void
    {
        // Clear existing
        try {
            if (DB::getDriverName() !== 'sqlite') {
                DB::statement('SET FOREIGN_KEY_CHECKS=0;');
            }

            DB::table('employees')->truncate();

            if (DB::getDriverName() !== 'sqlite') {
                DB::statement('SET FOREIGN_KEY_CHECKS=1;');
            }
        } catch (Exception $e) {
            $this->command->warn('Foreign checks skipped. Reason: '  . $e->getMessage());
        }
        
        $rows = [
            [
                'employee_firstname' => 'JOHN',
                'employee_middlename' => 'PAUL',
                'employee_lastname' => 'SMITH',
                'employee_suffix' => null,
                'employee_mother_maiden_name' => 'MARY ANN JONES',
                'employee_gender' => 'MALE',
                'employee_profile_picture' => null,
                'branch_id' => 1,
                'department_id' => 12,
                'employee_section' => 'HEAD OFFICE',
                'employee_status' => 1,

                'employee_birthdate' => '1995-05-15',
                'employee_birthplace' => 'QUEZON CITY',
                'employee_religion' => 'CATHOLIC',
                'employee_personal_email' => 'JOHN.SMITH@EXAMPLE.COM',
                'employee_contact_no1' => '09170000001',
                'employee_contact_no2' => null,
                'employee_viber_number' => null,
                'employee_educational_attainment' => 'BACHELOR',
                'employee_school_attended' => 'UNIVERSITY OF THE PHILIPPINES',
                'employee_college_course' => 'COMPUTER SCIENCE',
                'employee_position' => 'SOFTWARE ENGINEER',
                'employee_company_email' => 'JOHN.SMITH@COMPANY.COM',
                'employee_company_number' => 'LOCAL 1001',
                'employee_employment_type' => 'FULL TIME',
                'employee_civil_status' => 'SINGLE',
                'employee_marriage_certificate_path' => null,

                'employee_sss_updated' => 1,
                'employee_philhealth_updated' => 1,
                'employee_pagibig_updated' => 1,
                'employee_pagibig_mdf_path' => null,
                'employee_sss_number' => '34-1234567-1',
                'employee_philhealth_number' => '12-345678901-2',
                'employee_pagibig_number' => '1234-5678-9012',
                'employee_tin_number' => '123-456-789-000',

                'employee_father_name' => 'ROBERT SMITH',
                'employee_father_birthdate' => '1965-03-01',
                'employee_father_birth_certificate' => null,
                'employee_mother_name' => 'MARY ANN SMITH',
                'employee_mother_birthdate' => '1967-07-20',
                'employee_mother_birth_certificate' => null,
                'employee_blood_type' => 'O+',

                'employee_present_house_no' => '123',
                'employee_present_street' => 'KAMUNING ROAD',
                'employee_present_brgy' => 'KAMUNING',
                'employee_present_city' => 'QUEZON CITY',
                'employee_present_province' => 'METRO MANILA',
                'employee_present_zip_code' => '1103',

                'employee_permanent_house_no' => '123',
                'employee_permanent_street' => 'KAMUNING ROAD',
                'employee_permanent_brgy' => 'KAMUNING',
                'employee_permanent_city' => 'QUEZON CITY',
                'employee_permanent_province' => 'METRO MANILA',
                'employee_permanent_zip_code' => '1103',
            ],
            [
                'employee_firstname' => 'JANE',
                'employee_middlename' => 'MARIE',
                'employee_lastname' => 'DOE',
                'employee_suffix' => null,
                'employee_mother_maiden_name' => 'ALICE BROWN',
                'employee_gender' => 'FEMALE',
                'employee_profile_picture' => null,
                'branch_id' => 2,
                'department_id' => 10,
                'employee_section' => 'APPLICATIONS',
                'employee_status' => 1,

                'employee_birthdate' => '1997-02-20',
                'employee_birthplace' => 'MAKATI',
                'employee_religion' => 'CHRISTIAN',
                'employee_personal_email' => 'JANE.DOE@EXAMPLE.COM',
                'employee_contact_no1' => '09170000002',
                'employee_contact_no2' => null,
                'employee_viber_number' => null,
                'employee_educational_attainment' => 'BACHELOR',
                'employee_school_attended' => 'ATENEO DE MANILA UNIVERSITY',
                'employee_college_course' => 'INFORMATION SYSTEMS',
                'employee_position' => 'SYSTEMS ANALYST',
                'employee_company_email' => 'JANE.DOE@COMPANY.COM',
                'employee_company_number' => 'LOCAL 1002',
                'employee_employment_type' => 'FULL TIME',
                'employee_civil_status' => 'SINGLE',
                'employee_marriage_certificate_path' => null,

                'employee_sss_updated' => 1,
                'employee_philhealth_updated' => 1,
                'employee_pagibig_updated' => 1,
                'employee_pagibig_mdf_path' => null,
                'employee_sss_number' => '34-1234567-2',
                'employee_philhealth_number' => '12-345678901-3',
                'employee_pagibig_number' => '1234-5678-9013',
                'employee_tin_number' => '123-456-789-001',

                'employee_father_name' => 'MICHAEL DOE',
                'employee_father_birthdate' => '1964-01-15',
                'employee_father_birth_certificate' => null,
                'employee_mother_name' => 'ALICE DOE',
                'employee_mother_birthdate' => '1966-06-13',
                'employee_mother_birth_certificate' => null,
                'employee_blood_type' => 'A+',

                'employee_present_house_no' => '45',
                'employee_present_street' => 'PASEO DE ROXAS',
                'employee_present_brgy' => 'BEL-AIR',
                'employee_present_city' => 'MAKATI',
                'employee_present_province' => 'METRO MANILA',
                'employee_present_zip_code' => '1209',

                'employee_permanent_house_no' => '45',
                'employee_permanent_street' => 'PASEO DE ROXAS',
                'employee_permanent_brgy' => 'BEL-AIR',
                'employee_permanent_city' => 'MAKATI',
                'employee_permanent_province' => 'METRO MANILA',
                'employee_permanent_zip_code' => '1209',
            ],
            // 8 more employees below (all caps, required fields filled)
            [
                'employee_firstname' => 'ROBERT',
                'employee_middlename' => 'LEE',
                'employee_lastname' => 'JOHNSON',
                'employee_suffix' => null,
                'employee_mother_maiden_name' => 'LINDA PARK',
                'employee_gender' => 'MALE',
                'employee_profile_picture' => null,
                'branch_id' => 3,
                'department_id' => 7,
                'employee_section' => 'ACCOUNTING OPS',
                'employee_status' => 1,

                'employee_birthdate' => '1990-07-10',
                'employee_birthplace' => 'CEBU CITY',
                'employee_religion' => 'CATHOLIC',
                'employee_personal_email' => 'ROBERT.JOHNSON@EXAMPLE.COM',
                'employee_contact_no1' => '09170000003',
                'employee_contact_no2' => null,
                'employee_viber_number' => null,
                'employee_educational_attainment' => 'BACHELOR',
                'employee_school_attended' => 'UNIVERSITY OF SAN CARLOS',
                'employee_college_course' => 'ACCOUNTANCY',
                'employee_position' => 'ACCOUNTANT',
                'employee_company_email' => 'ROBERT.JOHNSON@COMPANY.COM',
                'employee_company_number' => 'LOCAL 1003',
                'employee_employment_type' => 'FULL TIME',
                'employee_civil_status' => 'MARRIED',
                'employee_marriage_certificate_path' => null,

                'employee_sss_updated' => 1,
                'employee_philhealth_updated' => 1,
                'employee_pagibig_updated' => 1,
                'employee_pagibig_mdf_path' => null,
                'employee_sss_number' => '34-1234567-3',
                'employee_philhealth_number' => '12-345678901-4',
                'employee_pagibig_number' => '1234-5678-9014',
                'employee_tin_number' => '123-456-789-002',

                'employee_father_name' => 'ALAN JOHNSON',
                'employee_father_birthdate' => '1962-05-03',
                'employee_father_birth_certificate' => null,
                'employee_mother_name' => 'LINDA JOHNSON',
                'employee_mother_birthdate' => '1963-09-18',
                'employee_mother_birth_certificate' => null,
                'employee_blood_type' => 'B+',

                'employee_present_house_no' => '10',
                'employee_present_street' => 'JONES AVENUE',
                'employee_present_brgy' => 'KALUBIHAN',
                'employee_present_city' => 'CEBU CITY',
                'employee_present_province' => 'CEBU',
                'employee_present_zip_code' => '6000',

                'employee_permanent_house_no' => '10',
                'employee_permanent_street' => 'JONES AVENUE',
                'employee_permanent_brgy' => 'KALUBIHAN',
                'employee_permanent_city' => 'CEBU CITY',
                'employee_permanent_province' => 'CEBU',
                'employee_permanent_zip_code' => '6000',
            ],
            [
                'employee_firstname' => 'LINDA',
                'employee_middlename' => 'ANNE',
                'employee_lastname' => 'BROWN',
                'employee_suffix' => null,
                'employee_mother_maiden_name' => 'SUSAN MILLER',
                'employee_gender' => 'FEMALE',
                'employee_profile_picture' => null,
                'branch_id' => 4,
                'department_id' => 4,
                'employee_section' => 'MARCOMM OPS',
                'employee_status' => 1,

                'employee_birthdate' => '1993-01-25',
                'employee_birthplace' => 'PAMPANGA',
                'employee_religion' => 'CATHOLIC',
                'employee_personal_email' => 'LINDA.BROWN@EXAMPLE.COM',
                'employee_contact_no1' => '09170000004',
                'employee_contact_no2' => null,
                'employee_viber_number' => null,
                'employee_educational_attainment' => 'BACHELOR',
                'employee_school_attended' => 'HOLY ANGEL UNIVERSITY',
                'employee_college_course' => 'COMMUNICATIONS',
                'employee_position' => 'GRAPHIC DESIGNER',
                'employee_company_email' => 'LINDA.BROWN@COMPANY.COM',
                'employee_company_number' => 'LOCAL 1004',
                'employee_employment_type' => 'FULL TIME',
                'employee_civil_status' => 'SINGLE',
                'employee_marriage_certificate_path' => null,

                'employee_sss_updated' => 1,
                'employee_philhealth_updated' => 1,
                'employee_pagibig_updated' => 1,
                'employee_pagibig_mdf_path' => null,
                'employee_sss_number' => '34-1234567-4',
                'employee_philhealth_number' => '12-345678901-5',
                'employee_pagibig_number' => '1234-5678-9015',
                'employee_tin_number' => '123-456-789-003',

                'employee_father_name' => 'THOMAS BROWN',
                'employee_father_birthdate' => '1963-03-14',
                'employee_father_birth_certificate' => null,
                'employee_mother_name' => 'SUSAN BROWN',
                'employee_mother_birthdate' => '1964-04-12',
                'employee_mother_birth_certificate' => null,
                'employee_blood_type' => 'A-',

                'employee_present_house_no' => '88',
                'employee_present_street' => 'MACARTHUR HIGHWAY',
                'employee_present_brgy' => 'SAN AGUSTIN',
                'employee_present_city' => 'CITY OF SAN FERNANDO',
                'employee_present_province' => 'PAMPANGA',
                'employee_present_zip_code' => '2000',

                'employee_permanent_house_no' => '88',
                'employee_permanent_street' => 'MACARTHUR HIGHWAY',
                'employee_permanent_brgy' => 'SAN AGUSTIN',
                'employee_permanent_city' => 'CITY OF SAN FERNANDO',
                'employee_permanent_province' => 'PAMPANGA',
                'employee_permanent_zip_code' => '2000',
            ],
            [
                'employee_firstname' => 'MICHAEL',
                'employee_middlename' => 'ALLEN',
                'employee_lastname' => 'DAVIS',
                'employee_suffix' => null,
                'employee_mother_maiden_name' => 'KAREN TAYLOR',
                'employee_gender' => 'MALE',
                'employee_profile_picture' => null,
                'branch_id' => 5,
                'department_id' => 7,
                'employee_section' => 'GENERAL ACCOUNTING',
                'employee_status' => 1,

                'employee_birthdate' => '1985-09-05',
                'employee_birthplace' => 'CEBU CITY',
                'employee_religion' => 'CATHOLIC',
                'employee_personal_email' => 'MICHAEL.DAVIS@EXAMPLE.COM',
                'employee_contact_no1' => '09170000005',
                'employee_contact_no2' => null,
                'employee_viber_number' => null,
                'employee_educational_attainment' => 'BACHELOR',
                'employee_school_attended' => 'UNIVERSITY OF CEBU',
                'employee_college_course' => 'ACCOUNTANCY',
                'employee_position' => 'SENIOR ACCOUNTANT',
                'employee_company_email' => 'MICHAEL.DAVIS@COMPANY.COM',
                'employee_company_number' => 'LOCAL 1005',
                'employee_employment_type' => 'FULL TIME',
                'employee_civil_status' => 'MARRIED',
                'employee_marriage_certificate_path' => null,

                'employee_sss_updated' => 1,
                'employee_philhealth_updated' => 1,
                'employee_pagibig_updated' => 1,
                'employee_pagibig_mdf_path' => null,
                'employee_sss_number' => '34-1234567-5',
                'employee_philhealth_number' => '12-345678901-6',
                'employee_pagibig_number' => '1234-5678-9016',
                'employee_tin_number' => '123-456-789-004',

                'employee_father_name' => 'DANIEL DAVIS',
                'employee_father_birthdate' => '1960-12-01',
                'employee_father_birth_certificate' => null,
                'employee_mother_name' => 'KAREN DAVIS',
                'employee_mother_birthdate' => '1962-02-02',
                'employee_mother_birth_certificate' => null,
                'employee_blood_type' => 'O-',

                'employee_present_house_no' => '50',
                'employee_present_street' => 'OSMEÑA BOULEVARD',
                'employee_present_brgy' => 'KALUBIHAN',
                'employee_present_city' => 'CEBU CITY',
                'employee_present_province' => 'CEBU',
                'employee_present_zip_code' => '6000',

                'employee_permanent_house_no' => '50',
                'employee_permanent_street' => 'OSMEÑA BOULEVARD',
                'employee_permanent_brgy' => 'KALUBIHAN',
                'employee_permanent_city' => 'CEBU CITY',
                'employee_permanent_province' => 'CEBU',
                'employee_permanent_zip_code' => '6000',
            ],
            [
                'employee_firstname' => 'SUSAN',
                'employee_middlename' => 'KAYE',
                'employee_lastname' => 'MILLER',
                'employee_suffix' => null,
                'employee_mother_maiden_name' => 'NANCY CLARK',
                'employee_gender' => 'FEMALE',
                'employee_profile_picture' => null,
                'branch_id' => 6,
                'department_id' => 8,
                'employee_section' => 'HR OPERATIONS',
                'employee_status' => 1,

                'employee_birthdate' => '1996-03-18',
                'employee_birthplace' => 'DAVAO CITY',
                'employee_religion' => 'CHRISTIAN',
                'employee_personal_email' => 'SUSAN.MILLER@EXAMPLE.COM',
                'employee_contact_no1' => '09170000006',
                'employee_contact_no2' => null,
                'employee_viber_number' => null,
                'employee_educational_attainment' => 'BACHELOR',
                'employee_school_attended' => 'UNIVERSITY OF MINDANAO',
                'employee_college_course' => 'PSYCHOLOGY',
                'employee_position' => 'HR SPECIALIST',
                'employee_company_email' => 'SUSAN.MILLER@COMPANY.COM',
                'employee_company_number' => 'LOCAL 1006',
                'employee_employment_type' => 'FULL TIME',
                'employee_civil_status' => 'SINGLE',
                'employee_marriage_certificate_path' => null,

                'employee_sss_updated' => 1,
                'employee_philhealth_updated' => 1,
                'employee_pagibig_updated' => 1,
                'employee_pagibig_mdf_path' => null,
                'employee_sss_number' => '34-1234567-6',
                'employee_philhealth_number' => '12-345678901-7',
                'employee_pagibig_number' => '1234-5678-9017',
                'employee_tin_number' => '123-456-789-005',

                'employee_father_name' => 'PETER MILLER',
                'employee_father_birthdate' => '1964-07-07',
                'employee_father_birth_certificate' => null,
                'employee_mother_name' => 'NANCY MILLER',
                'employee_mother_birthdate' => '1966-08-08',
                'employee_mother_birth_certificate' => null,
                'employee_blood_type' => 'AB+',

                'employee_present_house_no' => '12',
                'employee_present_street' => 'JP LAUREL AVENUE',
                'employee_present_brgy' => 'BAJADA',
                'employee_present_city' => 'DAVAO CITY',
                'employee_present_province' => 'DAVAO DEL SUR',
                'employee_present_zip_code' => '8000',

                'employee_permanent_house_no' => '12',
                'employee_permanent_street' => 'JP LAUREL AVENUE',
                'employee_permanent_brgy' => 'BAJADA',
                'employee_permanent_city' => 'DAVAO CITY',
                'employee_permanent_province' => 'DAVAO DEL SUR',
                'employee_permanent_zip_code' => '8000',
            ],
            [
                'employee_firstname' => 'DAVID',
                'employee_middlename' => 'MARK',
                'employee_lastname' => 'WILSON',
                'employee_suffix' => null,
                'employee_mother_maiden_name' => 'CAROL EVANS',
                'employee_gender' => 'MALE',
                'employee_profile_picture' => null,
                'branch_id' => 7,
                'department_id' => 12,
                'employee_section' => 'MEMBERSHIP MAIN',
                'employee_status' => 1,

                'employee_birthdate' => '1987-11-02',
                'employee_birthplace' => 'QUEZON CITY',
                'employee_religion' => 'CHRISTIAN',
                'employee_personal_email' => 'DAVID.WILSON@EXAMPLE.COM',
                'employee_contact_no1' => '09170000007',
                'employee_contact_no2' => null,
                'employee_viber_number' => null,
                'employee_educational_attainment' => 'BACHELOR',
                'employee_school_attended' => 'POLYTECHNIC UNIVERSITY OF THE PHILIPPINES',
                'employee_college_course' => 'BUSINESS ADMINISTRATION',
                'employee_position' => 'MEMBERSHIP OFFICER',
                'employee_company_email' => 'DAVID.WILSON@COMPANY.COM',
                'employee_company_number' => 'LOCAL 1007',
                'employee_employment_type' => 'FULL TIME',
                'employee_civil_status' => 'MARRIED',
                'employee_marriage_certificate_path' => null,

                'employee_sss_updated' => 1,
                'employee_philhealth_updated' => 1,
                'employee_pagibig_updated' => 1,
                'employee_pagibig_mdf_path' => null,
                'employee_sss_number' => '34-1234567-7',
                'employee_philhealth_number' => '12-345678901-8',
                'employee_pagibig_number' => '1234-5678-9018',
                'employee_tin_number' => '123-456-789-006',

                'employee_father_name' => 'EDWARD WILSON',
                'employee_father_birthdate' => '1961-10-10',
                'employee_father_birth_certificate' => null,
                'employee_mother_name' => 'CAROL WILSON',
                'employee_mother_birthdate' => '1963-03-03',
                'employee_mother_birth_certificate' => null,
                'employee_blood_type' => 'B-',

                'employee_present_house_no' => '77',
                'employee_present_street' => 'COMMONWEALTH AVENUE',
                'employee_present_brgy' => 'HOLY SPIRIT',
                'employee_present_city' => 'QUEZON CITY',
                'employee_present_province' => 'METRO MANILA',
                'employee_present_zip_code' => '1127',

                'employee_permanent_house_no' => '77',
                'employee_permanent_street' => 'COMMONWEALTH AVENUE',
                'employee_permanent_brgy' => 'HOLY SPIRIT',
                'employee_permanent_city' => 'QUEZON CITY',
                'employee_permanent_province' => 'METRO MANILA',
                'employee_permanent_zip_code' => '1127',
            ],
            [
                'employee_firstname' => 'KAREN',
                'employee_middlename' => 'ELIZABETH',
                'employee_lastname' => 'MOORE',
                'employee_suffix' => null,
                'employee_mother_maiden_name' => 'PATRICIA HALL',
                'employee_gender' => 'FEMALE',
                'employee_profile_picture' => null,
                'branch_id' => 8,
                'department_id' => 14,
                'employee_section' => 'MEMBERSHIP BALIWAG',
                'employee_status' => 1,

                'employee_birthdate' => '1998-06-12',
                'employee_birthplace' => 'BULACAN',
                'employee_religion' => 'CATHOLIC',
                'employee_personal_email' => 'KAREN.MOORE@EXAMPLE.COM',
                'employee_contact_no1' => '09170000008',
                'employee_contact_no2' => null,
                'employee_viber_number' => null,
                'employee_educational_attainment' => 'BACHELOR',
                'employee_school_attended' => 'BULACAN STATE UNIVERSITY',
                'employee_college_course' => 'MARKETING',
                'employee_position' => 'MEMBERSHIP ASSOCIATE',
                'employee_company_email' => 'KAREN.MOORE@COMPANY.COM',
                'employee_company_number' => 'LOCAL 1008',
                'employee_employment_type' => 'FULL TIME',
                'employee_civil_status' => 'SINGLE',
                'employee_marriage_certificate_path' => null,

                'employee_sss_updated' => 1,
                'employee_philhealth_updated' => 1,
                'employee_pagibig_updated' => 1,
                'employee_pagibig_mdf_path' => null,
                'employee_sss_number' => '34-1234567-8',
                'employee_philhealth_number' => '12-345678901-9',
                'employee_pagibig_number' => '1234-5678-9019',
                'employee_tin_number' => '123-456-789-007',

                'employee_father_name' => 'GEORGE MOORE',
                'employee_father_birthdate' => '1965-05-05',
                'employee_father_birth_certificate' => null,
                'employee_mother_name' => 'PATRICIA MOORE',
                'employee_mother_birthdate' => '1967-07-07',
                'employee_mother_birth_certificate' => null,
                'employee_blood_type' => 'A+',

                'employee_present_house_no' => '5',
                'employee_present_street' => 'J. P. RIZAL STREET',
                'employee_present_brgy' => 'PAGALA',
                'employee_present_city' => 'BALIWAG',
                'employee_present_province' => 'BULACAN',
                'employee_present_zip_code' => '3006',

                'employee_permanent_house_no' => '5',
                'employee_permanent_street' => 'J. P. RIZAL STREET',
                'employee_permanent_brgy' => 'PAGALA',
                'employee_permanent_city' => 'BALIWAG',
                'employee_permanent_province' => 'BULACAN',
                'employee_permanent_zip_code' => '3006',
            ],
            [
                'employee_firstname' => 'CHRISTOPHER',
                'employee_middlename' => 'JAMES',
                'employee_lastname' => 'TAYLOR',
                'employee_suffix' => null,
                'employee_mother_maiden_name' => 'STEPHANIE GREEN',
                'employee_gender' => 'MALE',
                'employee_profile_picture' => null,
                'branch_id' => 9,
                'department_id' => 15,
                'employee_section' => 'MEMBERSHIP DASMARIÑAS',
                'employee_status' => 1,

                'employee_birthdate' => '1994-04-09',
                'employee_birthplace' => 'CAVITE',
                'employee_religion' => 'CHRISTIAN',
                'employee_personal_email' => 'CHRISTOPHER.TAYLOR@EXAMPLE.COM',
                'employee_contact_no1' => '09170000009',
                'employee_contact_no2' => null,
                'employee_viber_number' => null,
                'employee_educational_attainment' => 'BACHELOR',
                'employee_school_attended' => 'DE LA SALLE UNIVERSITY - DASMARIÑAS',
                'employee_college_course' => 'BUSINESS MANAGEMENT',
                'employee_position' => 'MEMBERSHIP OFFICER',
                'employee_company_email' => 'CHRISTOPHER.TAYLOR@COMPANY.COM',
                'employee_company_number' => 'LOCAL 1009',
                'employee_employment_type' => 'FULL TIME',
                'employee_civil_status' => 'SINGLE',
                'employee_marriage_certificate_path' => null,

                'employee_sss_updated' => 1,
                'employee_philhealth_updated' => 1,
                'employee_pagibig_updated' => 1,
                'employee_pagibig_mdf_path' => null,
                'employee_sss_number' => '34-1234567-9',
                'employee_philhealth_number' => '12-345678901-0',
                'employee_pagibig_number' => '1234-5678-9020',
                'employee_tin_number' => '123-456-789-008',

                'employee_father_name' => 'RICHARD TAYLOR',
                'employee_father_birthdate' => '1962-02-22',
                'employee_father_birth_certificate' => null,
                'employee_mother_name' => 'STEPHANIE TAYLOR',
                'employee_mother_birthdate' => '1964-04-24',
                'employee_mother_birth_certificate' => null,
                'employee_blood_type' => 'O+',

                'employee_present_house_no' => '21',
                'employee_present_street' => 'MOLINO BOULEVARD',
                'employee_present_brgy' => 'MAMBALING',
                'employee_present_city' => 'DASMARINAS',
                'employee_present_province' => 'CAVITE',
                'employee_present_zip_code' => '4114',

                'employee_permanent_house_no' => '21',
                'employee_permanent_street' => 'MOLINO BOULEVARD',
                'employee_permanent_brgy' => 'MAMBALING',
                'employee_permanent_city' => 'DASMARINAS',
                'employee_permanent_province' => 'CAVITE',
                'employee_permanent_zip_code' => '4114',
            ],
            [
                'employee_firstname' => 'PATRICIA',
                'employee_middlename' => 'JOY',
                'employee_lastname' => 'ANDERSON',
                'employee_suffix' => null,
                'employee_mother_maiden_name' => 'HELEN COOPER',
                'employee_gender' => 'FEMALE',
                'employee_profile_picture' => null,
                'branch_id' => 10,
                'department_id' => 10,
                'employee_section' => 'IST OPERATIONS',
                'employee_status' => 1,

                'employee_birthdate' => '1999-08-23',
                'employee_birthplace' => 'PASIG',
                'employee_religion' => 'CHRISTIAN',
                'employee_personal_email' => 'PATRICIA.ANDERSON@EXAMPLE.COM',
                'employee_contact_no1' => '09170000010',
                'employee_contact_no2' => null,
                'employee_viber_number' => null,
                'employee_educational_attainment' => 'BACHELOR',
                'employee_school_attended' => 'UNIVERSITY OF THE EAST',
                'employee_college_course' => 'INFORMATION TECHNOLOGY',
                'employee_position' => 'IT SUPPORT',
                'employee_company_email' => 'PATRICIA.ANDERSON@COMPANY.COM',
                'employee_company_number' => 'LOCAL 1010',
                'employee_employment_type' => 'FULL TIME',
                'employee_civil_status' => 'SINGLE',
                'employee_marriage_certificate_path' => null,

                'employee_sss_updated' => 1,
                'employee_philhealth_updated' => 1,
                'employee_pagibig_updated' => 1,
                'employee_pagibig_mdf_path' => null,
                'employee_sss_number' => '34-1234567-0',
                'employee_philhealth_number' => '98-765432109-8',
                'employee_pagibig_number' => '1234-5678-9021',
                'employee_tin_number' => '123-456-789-009',

                'employee_father_name' => 'HAROLD ANDERSON',
                'employee_father_birthdate' => '1968-09-09',
                'employee_father_birth_certificate' => null,
                'employee_mother_name' => 'HELEN ANDERSON',
                'employee_mother_birthdate' => '1970-10-10',
                'employee_mother_birth_certificate' => null,
                'employee_blood_type' => 'AB-',

                'employee_present_house_no' => '9',
                'employee_present_street' => 'ORTIGAS AVENUE',
                'employee_present_brgy' => 'WACK-WACK',
                'employee_present_city' => 'MANDALUYONG',
                'employee_present_province' => 'METRO MANILA',
                'employee_present_zip_code' => '1555',

                'employee_permanent_house_no' => '9',
                'employee_permanent_street' => 'ORTIGAS AVENUE',
                'employee_permanent_brgy' => 'WACK-WACK',
                'employee_permanent_city' => 'MANDALUYONG',
                'employee_permanent_province' => 'METRO MANILA',
                'employee_permanent_zip_code' => '1555',
            ],
        ];

        DB::table('employees')->insert($rows);
    }
}
